### ISSUE TITLE
Escape special characters in command-line substitutions

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#175]
Question from @gflandin: who should escape special characters on the command line?

Maybe we could enforce that in `bosh`, by single-quoting all substituted values.

**Comment by glatard** [comment]
Proposal from the meeting: single-quote all substituted values

**Comment by jbpoline** [comment]
would shlex.quote()  be the python 3 tool for this ?
https://stackoverflow.com/questions/35817/how-to-escape-os-system-calls-in-python

**Comment by glatard** [comment]
`shlex.quote` only works in Python 3. Maybe we can fall back on `pipes.quote` when `shlex.quote` isn't there, as suggested here: https://stackoverflow.com/questions/26790916/python-3-backward-compatability-shlex-quote-vs-pipes-quote
```
try:
    from shlex import quote as cmd_quote
except ImportError:
    from pipes import quote as cmd_quote
```

**Comment by ramou** [comment]
When passing a single-quote-encapsulated string in my invocation I had some grief. The shell command told me it was:
```
blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'
```
which runs fine live, but gave an error message about formatted arguments from bosh (invoked programatically, though I think that's not an issue). The input of interest is `outfmt`

The invocation was:
```
		"invocation": {
			"archive": "out.asn",
			"outfmt": "'7 qacc sacc evalue qstart qend sstart send'",
			"out": "blast_formatter.out"
		},
```
You can invoke this through the tests (which fail do to the misinterpretation of the quotes), but I had trouble invoking through the command-line as I had to escape the single quotes and that messed stuff up. You can invoke the other variants through the command-line:

```
bosh exec launch ../blast_formatter.json '{"archive": "out.asn", "outfmt": "7 qacc sacc evalue qstart qend sstart send", "out": "blast_formatter.out"}'
```
does not work and yields the same _shell command_ as the broken test invocation above:
```
bin/blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'       -out blast_formatter.out
```

On the other hand, the following (which is what I changed the test invocation to in order to make it work) gives the desired result:

```
bosh exec launch ../blast_formatter.json '{"archive": "out.asn", "outfmt": "\"7 qacc sacc evalue qstart qend sstart send\"", "out": "blast_formatter.out"}'
```
works and yields the _shell command_:
```
bin/blast_formatter  -archive out.asn -outfmt '"7 qacc sacc evalue qstart qend sstart send"'       -out blast_formatter.out
```
I think the method by which strings passed as inputs should be quoted could be made explicit to perhaps resolve this interpretation, perhaps with the current default (single-quoting?). However, given that the single-qouted shell-command is actually a lie (not what actually gets run according to my tests), I think there is a problem in how things are being escaped... a quick look at the code makes me think it could be done in a clearer way that shows intent better.

All my tests were in Pthon 2.7. Does this warrant a new issue, or was it correct to attach it to this issue, which appears to be the source.
