### ISSUE TITLE
Allow tools to use a custom shell

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#188]
`bosh` currently uses `/bin/sh` to run the command line. The shell could be defined by the tool, and retrieved through the SHELL environment variable in the container. Discussed at the December meeting.

**Comment by glatard** [comment]
@laletscaria had issues with that as he was using `source` on his command line, which is not in `sh`.

**Comment by gkiar** [comment]
Then if we don't want to enforce a terminal and have people use things that will work for it (i.e. [the alternative to source](https://stackoverflow.com/a/4732283/1003437)), how about an additional field in a descriptor that specifies the path to the terminal, where we assume `/bin/bash` if not specified. Otherwise, it'll run a session using that shell.

**Comment by glatard** [comment]
absolutely, we should have a property containing the path to the desired shell, and use that shell in the shebang of the container script.
