### ISSUE TITLE
Support for various exit codes

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#36]
Exit codes could be associated to different meaning and messages depending on the tool.

**Comment by kofalt** [comment]
I would be cautious about this, simply because it means that every tool would need a boutiques wrapper to translate exit codes. A lot of stuff will exit with esoteric codes in the right circumstances.

One thing I've wanted for our use case was a "nothing to do here" indicator - if we launched an algorithm with an input that did not have enough data to QA, for example. I've considered things like providing a named pipe into the environment that it could write JSON to: progress & result reporting could be sent through there.

Alternatively you could leave files behind in a specific place: `touch /.boutique-failed`.

**Comment by glatard** [comment]
On the contrary, the tool would be able to advertise its own exit codes in the Boutiques descriptor. For instance, if exit code 123 means "input file 2 not found", then this error message could be part of the manifest and reported to the user when it occurs. The list of exist codes wouldn't have to be common across all tools, each tool could have its own. Does it make sense?

I have nothing against adding touch files in the spec though I don't like them personally (writing the touch file may fail).

**Comment by kofalt** [comment]
Aaah, yes that makes sense. I like that idea. We can default to assuming non-zero is a failure, unless it matches a code specified by the author to mean something different.
