### ISSUE TITLE
Allow value-only tags

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#385]
Right now tags must be in the form `key:value`. It would be good if we could also specify just values without a key. For example:
```
"tags": {
    "foo": "bar",
    "foo"
 }
```
Not sure if this is possible with the current version of JSON schema.

**Comment by glatard** [comment]
It isn't possible indeed, and I agree it would be nice to have that as the need occurred in a few situations. Not sure if we should remove key-value tags, which would make descriptors non backward compatible, or just support both.

**Comment by ramou** [comment]
I think we can get away with supporting both and with minimal effort being backwards compatible:

```
	"tags": [
		"blast", 
		"bioinformatics", 
		{
			"domain":[
				"makedatabse", 
				"foo", 
				"bar"
			]
		}
	]
```
which I would envision producing keywords: `blast`, `bioinformatics`, `domain:makeblastdb`, `domain:foo`, `domain:bar`

**Comment by ramou** [comment]
Well, not one line:

```
foo = json.loads('{"tags": {"domain":["makedatabse", "foo", "bar"]}}')
bar = json.loads('{"tags": [{"domain":["makedatabse", "foo", "bar"]}]}')

foo == bar

if isinstance(foo["tags"], dict):
    newtags = []
    for key,val in foo["tags"].iteritems():
        newtags.append({key:val})
    foo["tags"] = newtags
	
foo == bar
```

**Comment by ramou** [comment]
Python list comprehension let's me squeeze it a bit more
```
if isinstance(foo["tags"], dict):
    foo["tags"] = [{key:val} for key,val in foo["tags"].iteritems()]
```
Two lines. It can be squeezed to one except we'd cross 80 columns.

**Comment by ramou** [comment]
The changes are straight-forward within boutiques, and I'm happy with the minimalist approach to nudging. However, when updating how we export to carmin, I will need some guidance, if @glatard can direct me. Specifically, we are currently assigning the existing key/value pairs to `carmin_desc['properties']` in line 78 of exporter.py. I'll need an idea of where to look to understand how they want their properties used and depending on that, an idea of how we would want to fudge our alternate approach.

**Comment by ramou** [comment]
The best I've found so far is:
https://github.com/CARMIN-org/CARMIN-API/blob/23cb67bc6a641e2291b55fc1f58aa77ec09808e2/carmin.yaml#L584-L585

That last bit about being used in the `supportedPipelineProperties` concerns me. That said, it appears somewhat cyclic in its definition:
https://github.com/CARMIN-org/CARMIN-API/blob/23cb67bc6a641e2291b55fc1f58aa77ec09808e2/carmin.yaml#L527-L531

However, taking them both together it makes sense if I interpret that as prescriptive instead of descriptive. 

I think that leaves the main question as how we work around it. Keys are unique, so we wrap things with the same keys in an array, e.g.:
```
    "tags": {
        "domain": [
            "neuroinformatics",
            "diffusion",
            "mri",
            "bids"
        ]
    },
```
When we export for carmin, it will be communicated in the same key-value fashion as above. When we send it to zenodo, we're currently expanding it to `domain:neuroinformatics`, `domain:diffusion`, etc. What we'd like to see is something like:
```
    "tags": [
            "neuroinformatics",
            "diffusion",
            "mri",
            "bids",
            {"foo": [
                "bar",
                "zap"
            ]}        
    ],
```
which sends the tags as is (as keywords) to zenodo, but doesn't break exporting to carmin. My current suggestion is that we just accumulate all direct Strings like those above and them as is.  For Zenodo, we'd communicate an array of keywords:
```
    ["neuroinformatics", "diffusion", "mri", "bids", "foo:bar", "foo:zap"]
```
For Carmin descriptors we'd communicate the properties:
```
    carmin_desc['properties']["tags"] = ["neuroinformatics", "diffusion", "mri"]
    carmin_desc['properties']["foo"] = ["bar", "zap"]
```

**Comment by glatard** [comment]
From discussion at the meeting today: JSON schema has to be updated to support single-string tags.

**Comment by glatard** [comment]
From discussion at the meeting today:
1. CARMIN should be extended to support string-only tags (in addition to key-value pairs)
