### ISSUE TITLE
Explicit version consolidation

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#393]
Detecting existing versions based on tool name only isn't very robust, as one may want to update the tool name or correct typos in it. Instead, we should provided a `--replace <zenodo_id>` option in `bosh publish` that would consolidate the new publication with an existing one.

The existing name-based matching can be kept too, as it is optional anyway. The new one would provide a way to make sure that the record will be updated.

**Comment by erinb90** [comment]
So I wrote some code for this that I am pretty certain is good, but every time I try to publish an updated version of something on Sandbox I get a 400 error when trying to update the metadata of the new deposition version. It complains about not being allowed to update the doi, but I am not sending the doi in the data. I tried it without my changes and got the same thing. So I am really confused because it used to work fine. I sent a message to Zenodo support asking if they had any idea. If someone wants to try it on their machine and see if they get the same error please do. Just publish any descriptor to Sandbox, remove its doi and try to publish a new version.

**Comment by erinb90** [comment]
After some investigation I figured out that they recently changed their API such that it now requires you to send the doi when updating a deposition. If you don't send it, it will default to `''`, so it will think you are trying to change the doi to `''`, hence the error message saying I can't change the doi. I commented on their GitHub saying they should make this clear in the API docs.

**Comment by glatard** [comment]
@erinb90, does it mean that @shots47s' current issues with updating descriptors are coming from this API change, i.e., updating descriptors currently doesn't work?
