### ISSUE TITLE
zenodo.2597647 crashes pprint

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#459]
The FNIRT descriptor crashes `pprint` as it has two options with the same flag: `--applyinmask`. I guess we should:
1. Update the validator to check that all flags are unique
2. Fix the descriptor
3. Perhaps report this to Nipype?
What do you think @erinb90?

**Comment by erinb90** [comment]
Now that I look at my FNIRT descriptor again, I think I interpreted some of its Nipype input specs wrong. The second `--applyinmask` is actually an option to skip inmask when set. In Nipype they listed it as a boolean with command line flag `--applyinmask=0`, so in the descriptor I made a Number type with flag `--applyinmask` and options 0 or 1, but it should actually be a Flag type with command line flag `--applyinmask=0`. This would fix the flag uniqueness problem. I'll update the `nipype2boutiques` script to handle this case properly and update the descriptor.

**Comment by erinb90** [comment]
I noticed that FNIRT has a bunch of inputs that (according to Nipype) can be of different types. For cases like these, I create two separate, mutually exclusive inputs in the descriptor, for example inputs `config_file` and `config_file_2`. These inputs have the same command line flag but do not crash `pprint` (I tested it after fixing the `--applyinmask` thing). I looked a bit at the code for `pprint` and it seems that having the same command line flag is fine as long as the inputs also share the same command line key. @gkiar can you confirm?

**Comment by gkiar** [comment]
Hey @erinb90 - if I recall, the reason I parse the inputs by command-line key is so that I can populate a parser with them which could then regenerate the command-line using `bosh create` that would have things in the same order. In the case of `argparse`, and most parsers, you can indeed only have 1 definition of a given flag; if you need more, that's handled by internal logic of your script. So, your assessment of this only being supported in the case when they're *both* the same is correct - the type will be generic, and both sets of docstrings/min/max/etc will be passed along.

**Comment by erinb90** [comment]
Just published a new version of FNIRT at https://zenodo.org/record/2639849
