### ISSUE TITLE
Singularity mount paths

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#477]
When multiple directories are mounted in Singularity, `bosh` only mounts the largest common prefix between them: https://github.com/boutiques/boutiques/blame/d9ffd3ac3e2ca267753a4168660e8e2f2e23a0a6/tools/python/boutiques/localExec.py#L300-L331. This is meant to work around https://github.com/sylabs/singularity/issues/1469 that has been fixed in Singularity 2.5. 

However, this creates issues for some applications, and it's also a Singularity-specific complication in the code. We should just remove this logic and drop support for Singularity < 2.5. @gkiar, @shots47s, @ramou, any opinion?

@edickie

**Comment by ramou** [comment]
I don't know if this is related to the CBRAIN issue that is on my plate, but it certainly sounds like the same flavor. I think advancing support is always easier sooner than later. I think it removes a thing that we don't want in our code from our code, and if it creates a problem, it's probably a problem we'd have to face eventually anyway... and I'm suspicious that it may solve more problems than it creates (I've spun twice and spat over a dead chicken's shoulder to prevent that jinxing things).

**Comment by gkiar** [comment]
In what scenario does mounting an upstream directory cause a problem? If the user has access to and mounts `/home/a/` and `/home/b` but doesn't have access to `/home/`?

I support dropping older versions

**Comment by glatard** [comment]
From what I understand, user wants to mount `/home/a`, `/home/b`, but not `/home/c` because the code might have side effects on everything in `/home`.

**Comment by edickie** [comment]
More accurately, we want to be able to mount /home/a and /tmp/a without
mounting the whole file system...

**Comment by gabiherman** [comment]
The biggest functionality issue is that the singularity container uses paths relative to the directories that are mounted, and mounting the largest common prefix causes somewhat unpredictable behaviour.

So in the example of mriqc, say that my bids files are in "/home/a/data/bids", and I want my output in "/home/b/pipelines/mriqc". 
In the command line, I mount "/home/a/data/bids" and "/home/b/pipelines/mriqc", and my input json reads:
"bids_dir": "/bids"
"output_dir": "/mriqc"

If the -v mounting flag took the commands literally, this should work because the singularity container will contain /bids and /mriqc. The current behaviour of the script would be to override my flags and mount all of /home, which makes the paths in my input json incorrect. This means that before running a container, I would have to find the largest common path and edit the json accordingly every time.

Having an option to turn off the largest common prefix behaviour would allow us to use more consistent jsons.


...hopefully that made sense!

**Comment by glatard** [comment]
Thanks for the details @gabiherman, this will be part of the next release.
