### ISSUE TITLE
Work and file paths

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#51]
Some applications:
- need to be launched from a specific work directory in a container (add a string property for this). 
- only accept absolute file paths (add a boolean property to File inputs and outputs). 
- only accept relative file paths (add a boolean property to File inputs and outputs).

**Comment by glatard** [comment]
Note: input and output relative paths must be defined from the work directory.

**Comment by ttaa9** [comment]
I can understand this makes sense, in that it allows for greater customization.

But for cbrain specifically, I am not clear how this should be implemented. 

- For non-containerized tasks, the working directory is dynamically created based on the task id. So I don't know what specifying a launch directory would do. I'm also not sure how specifying absolute paths would be useful (for this non-docker case in cbrain). 

- For cbrain processes inside docker containers, would specifying the launch-directory simply mean we mount pwd to the target launch-directory, and then set that directory to the pwd (with `docker run ... -w`)? So the launch-directory must be an absolute path in this case, right? 

- What exactly would specifying that a file output path is absolute or relative do in cbrain? Should it check the output path value for each file and fail to launch if it is not absolute/relative? Also, for file inputs, they are given as userfiles and then their relative name only is written into the command template, I believe. So if `absolute-path` is given as true, should the input instead be replaced by the absolute path (and work as normal in all other cases)?

**Comment by glatard** [comment]
Yes, some applications only work from a particular directory.

* This is only for the containerized tasks. Should be part of the `container` object mentioned in #58.

* For CBRAIN, it won't change anything to the mounts. Mounts have to remain as is, otherwise symbolic links will be completely broken. We would only pass an extra `-w` option and possibly change file paths.

* For input files: if a path relative to the cbrain task execution dir is passed, then it should be transformed into a path relative to the container workdir. If an absolute path is passed, then nothing has to be changed.

* For output files: if the application produces files outside of the cbrain execution directory, they should be copied in the cbrain execution directory because this is the only one which is mounted. 

In fact I'm not sure that we really want to go for the container workdir, as it will complexify file management quite a lot and may lead to tricky bugs...

**Comment by ttaa9** [comment]
I see, so we would mount the same `-v ${PWD}:${PWD}` from the dynamically generated gridshare directory, but pass `-w container_workdir`. And then redirect all the relative input paths to be relative to the new pwd, and copy all the outputs back to the original mounted folder afterwards.

It seems like having the container workdir would at least complexify cbrain a bit. I'm pretty sure it could also be handled by just changing the command line, but of course having the option would be convenient for task programmers, I suppose. 

Still though, for my last bullet point above, if the container workdir is _not_ specified, then what exactly do you envision `absolute-path` and `relative-path` doing for inputs and outputs in cbrain? Since inputs as userfiles are always relative, I suppose specifying absolute simply means transforming the path to an absolute one. And I assume that, like above, any output file path outside of the mounted directory should be moved to the mounted directory at the end (using the bash script). 

If an absolute output path is given, say `/out/put` shall I tell cbrain to look for it by just copying it to `mountedDirectory/out/put` and then change the true output path in cbrain to be `./out/put` (without worrying about overwriting anything there, like another output specified relatively as `./out/put`)?

**Comment by glatard** [comment]
Yes to all :) I'm starting to realize that the command-line generation code is getting bigger and bigger. How about focusing on the local executor and replacing CBRAIN's bourreau side code by a call to this tool? It will not make the Bourreau implementation nicer, but it will certainly be more maintainable and testable. Just wondering.

**Comment by ttaa9** [comment]
Thanks! Certainly, keeping cbrain, the schema, the tools, and the cbrain-plugins-neuro descriptors simultaneously up-to-date is a challenge. 

That's an interesting idea, and certainly more maintainable. Basically then `cluster_commands` would just be a call to the script with the right parameters. I suppose you mean checking the input with an automatically generated invocation schema instead of that huge `after_form` method.

One potential issue might be that the errors from the json_schema python package during validation are often very hard to interpret (even worse than the ruby one). So an error translation system might be needed, if we want to give the user useful feedback. It might also make things a bit less flexible, if we wanted to make things work slightly differently in cbrain than the localexec handles it (although it can probably usually be done in pre/post-processing).

**Comment by glatard** [comment]
Exactly, `cluster_commands` would just call `localExecutor.py`. That's also a way to foster adoption in other platforms as properly supporting Boutiques requires a lot of coding yet. Is the local executor able to replace the "task generation code", i.e. the piece of code that decides how many tasks to generate with their parameters? 

The input validation stuff is a separate issue (the previous one can be implemented without it) but it is very relevant indeed. I guess the validator should then be worked on to better translate JSON validation issues. That's indeed a tricky decision to take since meaningful error reports are critical. 

You're again right about the fact that it makes things less flexible. However, Boutiques tools are like this as long as we integrate them automatically. If we want customization, we can still generate the CBRAIN classes and edit them manually.

Finally, maybe this discussion should be taken to the CBRAIN code base now. We could create two issues, to use the local executor and validator, respectively. OK?
