### ISSUE TITLE
More detailed version of "bosh version"

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#530]
Following #377 and #378, bosh is now capable of reporting its own version.

But it would be nice if it could report even more version information than just its own version. A command such as `bosh version --long` or `bosh version --detailed` could provide the version number of any or all of its major libraries.

Maybe even better would be a way to get the version information of the singularity or docker installation (as a special option for `bosh exec simulate` maybe?)

**Comment by glatard** [comment]
Hi @prioux, I believe `pip freeze` might be what you are looking for, am I right? As for singularity of Docker version, while I totally see the point tracking them, I'm not sure why it would be obtained through bosh rather than with the commands themselves. Are you thinking of a provenance record that would contain the versions of the dependencies that were actually used in an execution? In that case it would make sense to add this info to `bosh data` indeed.

**Comment by prioux** [comment]
Hi, I'm closing this because the original goal/impulse behind this was from the neurohub task provenance working group and I realize that in the end, the current 'bosh version' is pretty much all we really need. Sorry.
