### ISSUE TITLE
FileExistsError on Travis

### ISSUE THREAD

**Issue by djarecka** [boutiques/boutiques#610]
Boutiques gives me sometimes an error when run on travis: `FileExistsError: [Errno 17] File exists: '/home/travis/.cache/boutiques'`
see example: https://travis-ci.org/github/nipype/pydra/jobs/681324311

## Expected Behavior

perhaps you could handle this exception with boutiques

**Comment by DarrinFong** [comment]
Hello @djarecka, I can't find the `FileExistsError` in the [example](https://travis-ci.org/github/nipype/pydra/jobs/681324311). Could you elaborate on the issue? Thanks!

**Comment by ValHayot** [comment]
Hey @DarrinFong, I may have some insight on this (@djarecka, please correct me if I'm wrong). I believe this issue arises when running Boutiques in a multiprocessing environment. The issue lies with the if statements in [#L302-dataHandler.py](https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/dataHandler.py#L302). Essentially, if the cache dir doesn't exist and two parallel boutiques processes are trying to execute that same part of the code at the same type, they will both satisfy the if condition, except one will succeed in creating the directories and the other one will throw an error.

I suppose either adding an `exist_ok=True` to the `makedirs()` or using a try/except instead of an if-condition would resolve the error.

**Comment by glatard** [comment]
This should now be fixed but we can't test for sure. @djarecka, would you like us to ping you when we have a new release so that you can test and confirm?

**Comment by djarecka** [comment]
sorry for late answer, will test it today!

**Comment by djarecka** [comment]
having problem with installing develop version on travis: https://travis-ci.org/github/djarecka/pydra/jobs/695868414
any suggestions?

**Comment by glatard** [comment]
could it be because setup.py isn't at the root of the boutiques repo?
